### ISSUE TITLE
Rates api not working

### ISSUE THREAD

**Issue by ndegwakabue** [pioug/currency#1]
Hello, thanks for this great app. I reused ur app but now it is not displaying the current exchange rates. The link to my sample app is http://belva.co.ke/transferpesa/currencyapp.html. I checked the code and i think the rate API is not working http://aqueous-temple-6169.herokuapp.com/api/v1/rate/. Please help out.

**Comment by pioug** [comment]
The API server is hosted on a free Heroku instance (https://www.heroku.com/pricing). Since I am using the free tier, the "dyno" becomes idle after some inactivity and it needs some time to wake it up.

```
Free
Ideal for experimenting with cloud applications in a limited sandbox.
SLEEPS AFTER 30 MINS OF INACTIVITY
MUST SLEEP 6 HOURS IN A 24 HOUR PERIOD
```

It is really slow but it is working http://aqueous-temple-6169.herokuapp.com/api/v1/rate/eur/usd. I don't recommend you using this endpoint for an app in production.
